ROLES_PERMISSIONS = {
    "sales": [
        "create-client",
        "list-clients",
        "update-contract",
        "update-client",
        "delete-client",
        "list-contracts",
        "create-event",
        "list-collaborators",
        "list-unpaid-contracts",
        "list-unsigned-contracts",
        "list-events",
    ],
    "support": [
        "list-collaborators",
        "list-contracts",
        "list-clients",
        "list-events",
        "update-event",
    ],
    "management": [
        "create-contract",
        "create-collaborator",
        "delete-collaborator",
        "list-collaborators",
        "update-collaborator",
        "list-contracts",
        "list-clients",
        "list-events",
        "create-contract",
        "update-contract",
        "delete-contract",
        "update-event",
        "delete-event",
    ],
}
